<?php
/**
 * Country List Utility
 *
 * Provides a comprehensive list of countries with ISO codes
 * for use in forms and dropdowns.
 *
 * @package BuiltNorth\WPUtility
 * @subpackage Utilities
 * @since 1.0.0
 */

namespace BuiltNorth\WPUtility\Utilities;

class CountryList
{
	/**
	 * Country List
	 */
	public static function render()
	{
		return [
			'AF' => __('Afghanistan', 'polaris-forms'),
			'AL' => __('Albania', 'polaris-forms'),
			'DZ' => __('Algeria', 'polaris-forms'),
			'AD' => __('Andorra', 'polaris-forms'),
			'AO' => __('Angola', 'polaris-forms'),
			'AG' => __('Antigua and Barbuda', 'polaris-forms'),
			'AR' => __('Argentina', 'polaris-forms'),
			'AM' => __('Armenia', 'polaris-forms'),
			'AU' => __('Australia', 'polaris-forms'),
			'AT' => __('Austria', 'polaris-forms'),
			'AZ' => __('Azerbaijan', 'polaris-forms'),
			'BS' => __('Bahamas', 'polaris-forms'),
			'BH' => __('Bahrain', 'polaris-forms'),
			'BD' => __('Bangladesh', 'polaris-forms'),
			'BB' => __('Barbados', 'polaris-forms'),
			'BY' => __('Belarus', 'polaris-forms'),
			'BE' => __('Belgium', 'polaris-forms'),
			'BZ' => __('Belize', 'polaris-forms'),
			'BJ' => __('Benin', 'polaris-forms'),
			'BT' => __('Bhutan', 'polaris-forms'),
			'BO' => __('Bolivia', 'polaris-forms'),
			'BA' => __('Bosnia and Herzegovina', 'polaris-forms'),
			'BW' => __('Botswana', 'polaris-forms'),
			'BR' => __('Brazil', 'polaris-forms'),
			'BN' => __('Brunei', 'polaris-forms'),
			'BG' => __('Bulgaria', 'polaris-forms'),
			'BF' => __('Burkina Faso', 'polaris-forms'),
			'BI' => __('Burundi', 'polaris-forms'),
			'CV' => __('Cabo Verde', 'polaris-forms'),
			'KH' => __('Cambodia', 'polaris-forms'),
			'CM' => __('Cameroon', 'polaris-forms'),
			'CA' => __('Canada', 'polaris-forms'),
			'CF' => __('Central African Republic', 'polaris-forms'),
			'TD' => __('Chad', 'polaris-forms'),
			'CL' => __('Chile', 'polaris-forms'),
			'CN' => __('China', 'polaris-forms'),
			'CO' => __('Colombia', 'polaris-forms'),
			'KM' => __('Comoros', 'polaris-forms'),
			'CD' => __('Congo, Democratic Republic of the', 'polaris-forms'),
			'CG' => __('Congo, Republic of the', 'polaris-forms'),
			'CR' => __('Costa Rica', 'polaris-forms'),
			'HR' => __('Croatia', 'polaris-forms'),
			'CU' => __('Cuba', 'polaris-forms'),
			'CY' => __('Cyprus', 'polaris-forms'),
			'CZ' => __('Czech Republic', 'polaris-forms'),
			'DK' => __('Denmark', 'polaris-forms'),
			'DJ' => __('Djibouti', 'polaris-forms'),
			'DM' => __('Dominica', 'polaris-forms'),
			'DO' => __('Dominican Republic', 'polaris-forms'),
			'EC' => __('Ecuador', 'polaris-forms'),
			'EG' => __('Egypt', 'polaris-forms'),
			'SV' => __('El Salvador', 'polaris-forms'),
			'GQ' => __('Equatorial Guinea', 'polaris-forms'),
			'ER' => __('Eritrea', 'polaris-forms'),
			'EE' => __('Estonia', 'polaris-forms'),
			'SZ' => __('Eswatini', 'polaris-forms'),
			'ET' => __('Ethiopia', 'polaris-forms'),
			'FJ' => __('Fiji', 'polaris-forms'),
			'FI' => __('Finland', 'polaris-forms'),
			'FR' => __('France', 'polaris-forms'),
			'GA' => __('Gabon', 'polaris-forms'),
			'GM' => __('Gambia', 'polaris-forms'),
			'GE' => __('Georgia', 'polaris-forms'),
			'DE' => __('Germany', 'polaris-forms'),
			'GH' => __('Ghana', 'polaris-forms'),
			'GR' => __('Greece', 'polaris-forms'),
			'GD' => __('Grenada', 'polaris-forms'),
			'GT' => __('Guatemala', 'polaris-forms'),
			'GN' => __('Guinea', 'polaris-forms'),
			'GW' => __('Guinea-Bissau', 'polaris-forms'),
			'GY' => __('Guyana', 'polaris-forms'),
			'HT' => __('Haiti', 'polaris-forms'),
			'HN' => __('Honduras', 'polaris-forms'),
			'HU' => __('Hungary', 'polaris-forms'),
			'IS' => __('Iceland', 'polaris-forms'),
			'IN' => __('India', 'polaris-forms'),
			'ID' => __('Indonesia', 'polaris-forms'),
			'IR' => __('Iran', 'polaris-forms'),
			'IQ' => __('Iraq', 'polaris-forms'),
			'IE' => __('Ireland', 'polaris-forms'),
			'IL' => __('Israel', 'polaris-forms'),
			'IT' => __('Italy', 'polaris-forms'),
			'JM' => __('Jamaica', 'polaris-forms'),
			'JP' => __('Japan', 'polaris-forms'),
			'JO' => __('Jordan', 'polaris-forms'),
			'KZ' => __('Kazakhstan', 'polaris-forms'),
			'KE' => __('Kenya', 'polaris-forms'),
			'KI' => __('Kiribati', 'polaris-forms'),
			'KP' => __('Korea, North', 'polaris-forms'),
			'KR' => __('Korea, South', 'polaris-forms'),
			'XK' => __('Kosovo', 'polaris-forms'),
			'KW' => __('Kuwait', 'polaris-forms'),
			'KG' => __('Kyrgyzstan', 'polaris-forms'),
			'LA' => __('Laos', 'polaris-forms'),
			'LV' => __('Latvia', 'polaris-forms'),
			'LB' => __('Lebanon', 'polaris-forms'),
			'LS' => __('Lesotho', 'polaris-forms'),
			'LR' => __('Liberia', 'polaris-forms'),
			'LY' => __('Libya', 'polaris-forms'),
			'LI' => __('Liechtenstein', 'polaris-forms'),
			'LT' => __('Lithuania', 'polaris-forms'),
			'LU' => __('Luxembourg', 'polaris-forms'),
			'MG' => __('Madagascar', 'polaris-forms'),
			'MW' => __('Malawi', 'polaris-forms'),
			'MY' => __('Malaysia', 'polaris-forms'),
			'MV' => __('Maldives', 'polaris-forms'),
			'ML' => __('Mali', 'polaris-forms'),
			'MT' => __('Malta', 'polaris-forms'),
			'MH' => __('Marshall Islands', 'polaris-forms'),
			'MR' => __('Mauritania', 'polaris-forms'),
			'MU' => __('Mauritius', 'polaris-forms'),
			'MX' => __('Mexico', 'polaris-forms'),
			'FM' => __('Micronesia', 'polaris-forms'),
			'MD' => __('Moldova', 'polaris-forms'),
			'MC' => __('Monaco', 'polaris-forms'),
			'MN' => __('Mongolia', 'polaris-forms'),
			'ME' => __('Montenegro', 'polaris-forms'),
			'MA' => __('Morocco', 'polaris-forms'),
			'MZ' => __('Mozambique', 'polaris-forms'),
			'MM' => __('Myanmar', 'polaris-forms'),
			'NA' => __('Namibia', 'polaris-forms'),
			'NR' => __('Nauru', 'polaris-forms'),
			'NP' => __('Nepal', 'polaris-forms'),
			'NL' => __('Netherlands', 'polaris-forms'),
			'NZ' => __('New Zealand', 'polaris-forms'),
			'NI' => __('Nicaragua', 'polaris-forms'),
			'NE' => __('Niger', 'polaris-forms'),
			'NG' => __('Nigeria', 'polaris-forms'),
			'MK' => __('North Macedonia', 'polaris-forms'),
			'NO' => __('Norway', 'polaris-forms'),
			'OM' => __('Oman', 'polaris-forms'),
			'PK' => __('Pakistan', 'polaris-forms'),
			'PW' => __('Palau', 'polaris-forms'),
			'PS' => __('Palestine', 'polaris-forms'),
			'PA' => __('Panama', 'polaris-forms'),
			'PG' => __('Papua New Guinea', 'polaris-forms'),
			'PY' => __('Paraguay', 'polaris-forms'),
			'PE' => __('Peru', 'polaris-forms'),
			'PH' => __('Philippines', 'polaris-forms'),
			'PL' => __('Poland', 'polaris-forms'),
			'PT' => __('Portugal', 'polaris-forms'),
			'QA' => __('Qatar', 'polaris-forms'),
			'RO' => __('Romania', 'polaris-forms'),
			'RU' => __('Russia', 'polaris-forms'),
			'RW' => __('Rwanda', 'polaris-forms'),
			'KN' => __('Saint Kitts and Nevis', 'polaris-forms'),
			'LC' => __('Saint Lucia', 'polaris-forms'),
			'VC' => __('Saint Vincent and the Grenadines', 'polaris-forms'),
			'WS' => __('Samoa', 'polaris-forms'),
			'SM' => __('San Marino', 'polaris-forms'),
			'ST' => __('Sao Tome and Principe', 'polaris-forms'),
			'SA' => __('Saudi Arabia', 'polaris-forms'),
			'SN' => __('Senegal', 'polaris-forms'),
			'RS' => __('Serbia', 'polaris-forms'),
			'SC' => __('Seychelles', 'polaris-forms'),
			'SL' => __('Sierra Leone', 'polaris-forms'),
			'SG' => __('Singapore', 'polaris-forms'),
			'SK' => __('Slovakia', 'polaris-forms'),
			'SI' => __('Slovenia', 'polaris-forms'),
			'SB' => __('Solomon Islands', 'polaris-forms'),
			'SO' => __('Somalia', 'polaris-forms'),
			'ZA' => __('South Africa', 'polaris-forms'),
			'SS' => __('South Sudan', 'polaris-forms'),
			'ES' => __('Spain', 'polaris-forms'),
			'LK' => __('Sri Lanka', 'polaris-forms'),
			'SD' => __('Sudan', 'polaris-forms'),
			'SR' => __('Suriname', 'polaris-forms'),
			'SE' => __('Sweden', 'polaris-forms'),
			'CH' => __('Switzerland', 'polaris-forms'),
			'SY' => __('Syria', 'polaris-forms'),
			'TW' => __('Taiwan', 'polaris-forms'),
			'TJ' => __('Tajikistan', 'polaris-forms'),
			'TZ' => __('Tanzania', 'polaris-forms'),
			'TH' => __('Thailand', 'polaris-forms'),
			'TL' => __('Timor-Leste', 'polaris-forms'),
			'TG' => __('Togo', 'polaris-forms'),
			'TO' => __('Tonga', 'polaris-forms'),
			'TT' => __('Trinidad and Tobago', 'polaris-forms'),
			'TN' => __('Tunisia', 'polaris-forms'),
			'TR' => __('Turkey', 'polaris-forms'),
			'TM' => __('Turkmenistan', 'polaris-forms'),
			'TV' => __('Tuvalu', 'polaris-forms'),
			'UG' => __('Uganda', 'polaris-forms'),
			'UA' => __('Ukraine', 'polaris-forms'),
			'AE' => __('United Arab Emirates', 'polaris-forms'),
			'GB' => __('United Kingdom', 'polaris-forms'),
			'US' => __('United States', 'polaris-forms'),
			'UY' => __('Uruguay', 'polaris-forms'),
			'UZ' => __('Uzbekistan', 'polaris-forms'),
			'VU' => __('Vanuatu', 'polaris-forms'),
			'VA' => __('Vatican City', 'polaris-forms'),
			'VE' => __('Venezuela', 'polaris-forms'),
			'VN' => __('Vietnam', 'polaris-forms'),
			'YE' => __('Yemen', 'polaris-forms'),
			'ZM' => __('Zambia', 'polaris-forms'),
			'ZW' => __('Zimbabwe', 'polaris-forms'),
		];
	}
}
